"""Channel guard userbot.

Every ROTATE_MINUTES it revokes the channel's primary invite link, issues a
fresh one, and DMs it to the owner. Anyone who joins the channel directly is
permanently banned; the owner and admins are exempt. On startup it preserves
existing bans and runs a security sweep (ban all non-admin members), then
re-sweeps every SWEEP_MINUTES to catch anyone the live handler missed.

The logged-in account must be an ADMIN of the channel with "Invite users via
link" and "Ban users" rights.

Run:  python guard.py    (Ctrl+C to stop)
"""
from __future__ import annotations

import asyncio
from pathlib import Path

from telethon import TelegramClient, events
from telethon.errors import FloodWaitError
from telethon.tl.functions.channels import EditBannedRequest
from telethon.tl.functions.messages import ExportChatInviteRequest
from telethon.tl.types import (
    ChannelParticipantAdmin,
    ChannelParticipantBanned,
    ChannelParticipantCreator,
    ChannelParticipantLeft,
    ChatBannedRights,
    UpdateChannelParticipant,
)

import config
import linkstore
import ui
from runtime_lock import ProcessLock, host_lock_path

# Permanent remove-from-channel rights.
_KICK_RIGHTS = ChatBannedRights(until_date=None, view_messages=True)

client: TelegramClient | None = None
_state = {"self_id": 0, "channel": None, "channel_id": 0, "owner": None, "owner_id": 0}
_kicks_in_flight: set[int] = set()
_background_tasks: set[asyncio.Task] = set()
_instance_locks: list[ProcessLock] = []


def _acquire_guard_lock(path: Path) -> bool:
    lock = ProcessLock(path)
    if not lock.acquire():
        return False
    _instance_locks.append(lock)
    return True


def _close_guard_locks() -> None:
    while _instance_locks:
        _instance_locks.pop().close()


async def notify(text: str) -> None:
    try:
        await client.send_message(_state["owner"], text, parse_mode="html",
                                  link_preview=False)
    except Exception as e:  # noqa: BLE001
        print(f"owner DM failed: {type(e).__name__}: {e}")


async def rotate_once() -> None:
    """Revoke the current primary invite link, issue a new one, DM the owner."""
    res = await client(ExportChatInviteRequest(
        _state["channel"], legacy_revoke_permanent=True,
    ))
    link = res.link
    title = getattr(_state["channel"], "title", "channel")
    # Publish to a guard-owned handoff before the DM arrives. quickreply.py
    # validates against this value, so links generated by the admin bot can
    # never replace the Business /demo shortcut.
    try:
        linkstore.save_demo_link(link)
    except Exception as e:  # noqa: BLE001
        print(f"demo link handoff failed: {type(e).__name__}: {e}")
    await notify(f"<b>{title}</b>\n<code>{link}</code>")
    print(ui.green("[link] ") + f"rotated -> {ui.bold(link)}")


async def rotate_loop() -> None:
    while True:
        try:
            await rotate_once()
        except Exception as e:  # noqa: BLE001
            print(f"rotate failed: {type(e).__name__}: {e}")
            await notify(f"Link rotation failed: {type(e).__name__}")
        await asyncio.sleep(config.ROTATE_MINUTES * 60)


async def _resolve_user(user):
    """A fully-resolved input peer (with access hash). A raw int often resolves
    to an incomplete peer that the ban silently no-ops on."""
    if not isinstance(user, int):
        return user
    try:
        return await client.get_input_entity(user)
    except Exception:
        return user


async def kick(user, announce: bool = True) -> bool:
    """Permanently ban a direct joiner. Returns True when Telegram accepted it."""
    uid = user if isinstance(user, int) else getattr(user, "id", user)
    if uid in (_state["self_id"], _state["owner_id"]):
        return False
    try:
        target = await _resolve_user(user)
        await client(EditBannedRequest(_state["channel"], target, _KICK_RIGHTS))
        print(ui.yellow("[ban] ") + f"permanently banned {uid}")
        if announce:
            await notify(f"Permanently banned <code>{uid}</code>")
        return True
    except Exception as e:  # noqa: BLE001 - e.g. admins can't be kicked
        print(ui.red("[kick] ") + f"{uid} failed: {type(e).__name__}: {e}")
        return False


async def _member_count() -> int | None:
    try:
        return (await client.get_participants(_state["channel"], limit=1)).total
    except Exception:
        return None


async def _set_banned(user, rights) -> bool:
    """Apply banned rights to one user (resolves a full peer first). Waits out
    short flood limits. Returns True on success."""
    target = await _resolve_user(user)
    for _ in range(2):
        try:
            await client(EditBannedRequest(_state["channel"], target, rights))
            return True
        except FloodWaitError as e:
            await asyncio.sleep(min(int(e.seconds), 60) + 1)
        except Exception as e:  # noqa: BLE001
            print(ui.red("[ban] ") + f"{getattr(user, 'id', user)}: {type(e).__name__}")
            return False
    return False


async def sweep_members() -> int:
    """Permanently ban every non-admin member found by the security sweep."""
    channel = _state["channel"]
    before = await _member_count()

    # Collect all non-admin members first.
    targets = []
    try:
        async for user in client.iter_participants(channel):
            if user.id in (_state["self_id"], _state["owner_id"]):
                continue
            p = getattr(user, "participant", None)
            if isinstance(p, (ChannelParticipantCreator, ChannelParticipantAdmin)):
                continue  # keep admins/creator
            targets.append(user)
    except Exception as e:  # noqa: BLE001
        print(ui.red("[sweep] ") + f"list failed: {type(e).__name__}: {e}")

    # Ban everyone (removes them and prevents the same account rejoining).
    banned = []
    for user in targets:
        if await _set_banned(user, _KICK_RIGHTS):
            banned.append(user)
            print(ui.yellow("[ban] ") + f"removed {user.id}")
            await asyncio.sleep(0.2)

    after = await _member_count()
    if before is not None and after is not None:
        print(ui.dim(f"[sweep] members {before} -> {after}"))
        if banned and after >= before:
            ui.warn("Banned users but the member count didn't drop — this "
                    "account likely can't remove users here (needs full admin "
                    "with 'Ban users').")
    return len(banned)


async def sweep_loop() -> None:
    if config.SWEEP_MINUTES <= 0:
        return
    while True:
        await asyncio.sleep(config.SWEEP_MINUTES * 60)
        try:
            n = await sweep_members()
            if n:
                print(ui.yellow("[sweep] ") + f"removed {n} member(s)")
                await notify(f"Security sweep removed <b>{n}</b> member(s).")
        except Exception as error:  # noqa: BLE001
            ui.error(f"security sweep failed: {type(error).__name__}: {error}")


def _can_ban(channel) -> bool:
    """Whether this account can remove users (creator, or admin with ban_users)."""
    if getattr(channel, "creator", False):
        return True
    ar = getattr(channel, "admin_rights", None)
    return bool(ar and getattr(ar, "ban_users", False))


async def _kick_once(user_id: int) -> None:
    """Collapse overlapping notifications only while a kick is in flight."""
    if user_id in _kicks_in_flight:
        return
    _kicks_in_flight.add(user_id)
    try:
        await kick(user_id)
    finally:
        _kicks_in_flight.discard(user_id)


def _start_background(coro, name: str) -> None:
    task = asyncio.create_task(coro, name=name)
    _background_tasks.add(task)

    def finished(done: asyncio.Task) -> None:
        _background_tasks.discard(done)
        if done.cancelled():
            return
        error = done.exception()
        if error is not None:
            ui.error(f"{done.get_name()} stopped: {type(error).__name__}: {error}")

    task.add_done_callback(finished)


async def on_participant(update):
    if not isinstance(update, UpdateChannelParticipant):
        return
    if _state["channel_id"] and update.channel_id != _state["channel_id"]:
        return
    previous_outside = update.prev_participant is None or isinstance(
        update.prev_participant, (ChannelParticipantLeft, ChannelParticipantBanned)
    )
    current_inside = update.new_participant is not None and not isinstance(
        update.new_participant, (ChannelParticipantLeft, ChannelParticipantBanned)
    )
    joined = previous_outside and current_inside
    print(ui.dim(
        f"[participant] user={update.user_id} "
        f"prev={type(update.prev_participant).__name__ if update.prev_participant else None} "
        f"new={type(update.new_participant).__name__ if update.new_participant else None}"
        f" -> {'JOIN' if joined else 'change'}"
    ))
    if joined:
        await _kick_once(update.user_id)


async def on_chat_action(event):
    """Backup path (fires for supergroups; broadcast channels use the raw update)."""
    if not (event.user_joined or event.user_added):
        return
    for uid in (event.user_ids or ([event.user_id] if event.user_id else [])):
        await _kick_once(uid)


async def main() -> None:
    global client
    config.require("API_ID", "API_HASH")
    session_lock = host_lock_path(
        "guard-session", str(Path(config.SESSION).resolve())
    )
    if not _acquire_guard_lock(session_lock):
        ui.error(f"Another guard.py owns the session lock {session_lock}.")
        raise SystemExit(1)

    client = TelegramClient(config.SESSION, config.API_ID, config.API_HASH)
    await client.start()  # prompts phone + OTP on first run

    me = await client.get_me()
    account_lock = host_lock_path("guard-account", str(me.id))
    if not _acquire_guard_lock(account_lock):
        ui.error(
            "Another checkout is already running guard.py for this Telegram "
            "account."
        )
        await client.disconnect()
        _close_guard_locks()
        raise SystemExit(1)
    _state["self_id"] = me.id

    from resolve import choose_channel, resolve_channel

    # --- channel (pick from a list if the configured one isn't usable) ------
    channel = None
    if config.CHANNEL_RAW.strip():
        channel = await resolve_channel(client, config.channel())
        if channel is None:
            ui.warn(f"Could not use CHANNEL={config.CHANNEL_RAW!r}. Pick one below.")
    while channel is None:
        value = await choose_channel(client)
        channel = await resolve_channel(client, config.coerce(value))
        if channel is None:
            ui.warn("Couldn't access that one — try another.")
            continue
        config.save_env({"CHANNEL": value})
    _state["channel"] = channel
    _state["channel_id"] = channel.id

    if not _can_ban(channel):
        ui.warn("This account is NOT an admin with 'Ban users' rights on that "
                "channel — auto-kick WON'T work (Telegram won't send join "
                "updates and kicks are rejected). Make it an admin with the "
                "'Ban users' right, then restart.")

    # --- owner --------------------------------------------------------------
    owner_val = config.owner()
    if not owner_val:
        raw = input("\nOwner username or user id (receives the links): ").strip()
        config.save_env({"OWNER": raw})
        owner_val = config.coerce(raw)
    try:
        owner = await client.get_entity(owner_val)
    except Exception as e:  # noqa: BLE001
        ui.error(f"Couldn't resolve owner {owner_val!r}: {type(e).__name__}.")
        ui.info("Use a @username, or make sure the account has a chat with the "
                "userbot (or is in the channel).")
        await client.disconnect()
        _close_guard_locks()
        return
    _state["owner"] = owner
    _state["owner_id"] = owner.id

    # --- startup security sweep (catch offline joins) -----------------------
    swept = await sweep_members()
    if swept:
        ui.success(f"Startup sweep removed {swept} non-admin member(s).")
        await notify(f"Startup sweep removed <b>{swept}</b> member(s).")

    # --- run ----------------------------------------------------------------
    # Raw participant updates catch broadcast-channel joins; ChatAction is a
    # backup for supergroups. Listen to ALL raw updates and filter in-handler
    # (a type-filtered Raw can miss updates on some layers).
    client.add_event_handler(on_participant, events.Raw)
    client.add_event_handler(on_chat_action, events.ChatAction(chats=channel))
    _start_background(rotate_loop(), "link-rotation")
    _start_background(sweep_loop(), "security-sweep")

    sweep_note = (f"security sweep every {config.SWEEP_MINUTES:g} min; "
                  if config.SWEEP_MINUTES > 0 else "")
    title = getattr(channel, "title", channel)
    ui.banner("Channel guard - running")
    ui.success(f"Guarding: {ui.bold(str(title))}")
    ui.info(f"Owner: {getattr(owner, 'first_name', owner.id)} (id {owner.id})")
    ui.info(f"Rotating invite link every {ui.bold(f'{config.ROTATE_MINUTES:g}')} min; "
            f"{sweep_note}unauthorized joiners are permanently banned. "
            + ui.dim("Ctrl+C to stop."))
    try:
        await client.run_until_disconnected()
    finally:
        for task in list(_background_tasks):
            task.cancel()
        if _background_tasks:
            await asyncio.gather(*_background_tasks, return_exceptions=True)
        _close_guard_locks()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nStopped.")
