"""Channel guard userbot.

Every ROTATE_MINUTES it revokes the channel's primary invite link, issues a
fresh one, and DMs it to the owner. Anyone who joins the channel is immediately
kicked AND unbanned (removed but free to rejoin — never a lasting ban); the
owner and admins are exempt. On startup it clears every existing ban and runs a
security sweep (kick all non-admin members), then re-sweeps every SWEEP_MINUTES
to catch anyone the live handler missed.

The logged-in account must be an ADMIN of the channel with "Invite users via
link" and "Ban users" rights.

Run:  python guard.py    (Ctrl+C to stop)
"""
from __future__ import annotations

import asyncio

from telethon import TelegramClient, events
from telethon.errors import FloodWaitError
from telethon.tl.functions.channels import EditBannedRequest, GetParticipantsRequest
from telethon.tl.functions.messages import ExportChatInviteRequest
from telethon.tl.types import (
    ChannelParticipantAdmin,
    ChannelParticipantCreator,
    ChannelParticipantsKicked,
    ChatBannedRights,
    UpdateChannelParticipant,
)

import config
import linkstore
import ui

# Remove-from-channel rights (ban), and cleared rights (unban).
_KICK_RIGHTS = ChatBannedRights(until_date=None, view_messages=True)
_UNBAN_RIGHTS = ChatBannedRights(until_date=None)

client: TelegramClient | None = None
_state = {"self_id": 0, "channel": None, "channel_id": 0, "owner": None, "owner_id": 0}


async def notify(text: str) -> None:
    try:
        await client.send_message(_state["owner"], text, parse_mode="html",
                                  link_preview=False)
    except Exception as e:  # noqa: BLE001
        print(f"owner DM failed: {type(e).__name__}: {e}")


async def rotate_once() -> None:
    """Revoke the current primary invite link, issue a new one, DM the owner."""
    res = await client(ExportChatInviteRequest(
        _state["channel"], legacy_revoke_permanent=True,
    ))
    link = res.link
    title = getattr(_state["channel"], "title", "channel")
    # Publish to a guard-owned handoff before the DM arrives. quickreply.py
    # validates against this value, so links generated by the admin bot can
    # never replace the Business /demo shortcut.
    try:
        linkstore.save_demo_link(link)
    except Exception as e:  # noqa: BLE001
        print(f"demo link handoff failed: {type(e).__name__}: {e}")
    await notify(f"<b>{title}</b>\n<code>{link}</code>")
    print(ui.green("[link] ") + f"rotated -> {ui.bold(link)}")


async def rotate_loop() -> None:
    while True:
        try:
            await rotate_once()
        except Exception as e:  # noqa: BLE001
            print(f"rotate failed: {type(e).__name__}: {e}")
            await notify(f"Link rotation failed: {type(e).__name__}")
        await asyncio.sleep(config.ROTATE_MINUTES * 60)


async def _resolve_user(user):
    """A fully-resolved input peer (with access hash). A raw int often resolves
    to an incomplete peer that the ban silently no-ops on."""
    if not isinstance(user, int):
        return user
    try:
        return await client.get_input_entity(user)
    except Exception:
        return user


async def kick(user, announce: bool = True) -> bool:
    """Remove the user via kick_participant (ban+unban, no lasting ban). Returns
    True if removed. `user` may be an entity (preferred) or a raw id."""
    uid = user if isinstance(user, int) else getattr(user, "id", user)
    if uid in (_state["self_id"], _state["owner_id"]):
        return False
    try:
        target = await _resolve_user(user)
        # kick_participant bans then immediately unbans -> removed, not banned.
        await client.kick_participant(_state["channel"], target)
        print(ui.yellow("[kick] ") + f"removed {uid}")
        if announce:
            await notify(f"Kicked <code>{uid}</code>")
        return True
    except Exception as e:  # noqa: BLE001 - e.g. admins can't be kicked
        print(ui.red("[kick] ") + f"{uid} failed: {type(e).__name__}: {e}")
        return False


async def _member_count() -> int | None:
    try:
        return (await client.get_participants(_state["channel"], limit=1)).total
    except Exception:
        return None


async def _set_banned(user, rights) -> bool:
    """Apply banned rights to one user (resolves a full peer first). Waits out
    short flood limits. Returns True on success."""
    target = await _resolve_user(user)
    for _ in range(2):
        try:
            await client(EditBannedRequest(_state["channel"], target, rights))
            return True
        except FloodWaitError as e:
            await asyncio.sleep(min(int(e.seconds), 60) + 1)
        except Exception as e:  # noqa: BLE001
            print(ui.red("[ban] ") + f"{getattr(user, 'id', user)}: {type(e).__name__}")
            return False
    return False


async def sweep_members() -> int:
    """Security sweep in two phases: BAN every non-admin member first (that is
    what actually removes them), THEN unban them all so nobody is left banned."""
    channel = _state["channel"]
    before = await _member_count()

    # Collect all non-admin members first.
    targets = []
    try:
        async for user in client.iter_participants(channel):
            if user.id in (_state["self_id"], _state["owner_id"]):
                continue
            p = getattr(user, "participant", None)
            if isinstance(p, (ChannelParticipantCreator, ChannelParticipantAdmin)):
                continue  # keep admins/creator
            targets.append(user)
    except Exception as e:  # noqa: BLE001
        print(ui.red("[sweep] ") + f"list failed: {type(e).__name__}: {e}")

    # Phase 1 — ban everyone (removes them from the channel).
    banned = []
    for user in targets:
        if await _set_banned(user, _KICK_RIGHTS):
            banned.append(user)
            print(ui.yellow("[ban] ") + f"removed {user.id}")
            await asyncio.sleep(0.2)

    # Phase 2 — unban them all (kick, not a lasting ban).
    for user in banned:
        await _set_banned(user, _UNBAN_RIGHTS)
        await asyncio.sleep(0.2)
    if banned:
        print(ui.green("[unban] ") + f"cleared {len(banned)} ban(s)")

    after = await _member_count()
    if before is not None and after is not None:
        print(ui.dim(f"[sweep] members {before} -> {after}"))
        if banned and after >= before:
            ui.warn("Banned users but the member count didn't drop — this "
                    "account likely can't remove users here (needs full admin "
                    "with 'Ban users').")
    return len(banned)


async def sweep_loop() -> None:
    if config.SWEEP_MINUTES <= 0:
        return
    while True:
        await asyncio.sleep(config.SWEEP_MINUTES * 60)
        n = await sweep_members()
        if n:
            print(ui.yellow("[sweep] ") + f"removed {n} member(s)")
            await notify(f"Security sweep removed <b>{n}</b> member(s).")


async def unban_all() -> int:
    """Clear every existing ban in the channel (so nobody stays banned)."""
    channel = _state["channel"]
    cleared = 0
    offset = 0
    while True:
        try:
            res = await client(GetParticipantsRequest(
                channel, ChannelParticipantsKicked(q=""), offset, 100, hash=0,
            ))
        except Exception as e:  # noqa: BLE001
            print(ui.red("[unban] ") + f"list failed: {type(e).__name__}")
            break
        if not res.participants:
            break
        for p in res.participants:
            peer = getattr(p, "peer", None)
            if peer is None:
                continue
            try:
                await client(EditBannedRequest(channel, peer, _UNBAN_RIGHTS))
                cleared += 1
                await asyncio.sleep(0.2)
            except Exception:
                pass
        offset += len(res.participants)
        if len(res.participants) < 100:
            break
    return cleared


def _can_ban(channel) -> bool:
    """Whether this account can remove users (creator, or admin with ban_users)."""
    if getattr(channel, "creator", False):
        return True
    ar = getattr(channel, "admin_rights", None)
    return bool(ar and getattr(ar, "ban_users", False))


async def on_participant(update):
    if not isinstance(update, UpdateChannelParticipant):
        return
    if _state["channel_id"] and update.channel_id != _state["channel_id"]:
        return
    joined = update.prev_participant is None and update.new_participant is not None
    print(ui.dim(
        f"[participant] user={update.user_id} "
        f"prev={type(update.prev_participant).__name__ if update.prev_participant else None} "
        f"new={type(update.new_participant).__name__ if update.new_participant else None}"
        f" -> {'JOIN' if joined else 'change'}"
    ))
    if joined:
        await kick(update.user_id)


async def on_chat_action(event):
    """Backup path (fires for supergroups; broadcast channels use the raw update)."""
    if not (event.user_joined or event.user_added):
        return
    for uid in (event.user_ids or ([event.user_id] if event.user_id else [])):
        await kick(uid)


async def main() -> None:
    global client
    config.require("API_ID", "API_HASH")

    client = TelegramClient(config.SESSION, config.API_ID, config.API_HASH)
    await client.start()  # prompts phone + OTP on first run

    me = await client.get_me()
    _state["self_id"] = me.id

    from resolve import choose_channel, resolve_channel

    # --- channel (pick from a list if the configured one isn't usable) ------
    channel = None
    if config.CHANNEL_RAW.strip():
        channel = await resolve_channel(client, config.channel())
        if channel is None:
            ui.warn(f"Could not use CHANNEL={config.CHANNEL_RAW!r}. Pick one below.")
    while channel is None:
        value = await choose_channel(client)
        channel = await resolve_channel(client, config.coerce(value))
        if channel is None:
            ui.warn("Couldn't access that one — try another.")
            continue
        config.save_env({"CHANNEL": value})
    _state["channel"] = channel
    _state["channel_id"] = channel.id

    if not _can_ban(channel):
        ui.warn("This account is NOT an admin with 'Ban users' rights on that "
                "channel — auto-kick WON'T work (Telegram won't send join "
                "updates and kicks are rejected). Make it an admin with the "
                "'Ban users' right, then restart.")

    # --- owner --------------------------------------------------------------
    owner_val = config.owner()
    if not owner_val:
        raw = input("\nOwner username or user id (receives the links): ").strip()
        config.save_env({"OWNER": raw})
        owner_val = config.coerce(raw)
    try:
        owner = await client.get_entity(owner_val)
    except Exception as e:  # noqa: BLE001
        ui.error(f"Couldn't resolve owner {owner_val!r}: {type(e).__name__}.")
        ui.info("Use a @username, or make sure the account has a chat with the "
                "userbot (or is in the channel).")
        await client.disconnect()
        return
    _state["owner"] = owner
    _state["owner_id"] = owner.id

    # --- clear any existing bans up front -----------------------------------
    cleared = await unban_all()
    if cleared:
        ui.success(f"Unbanned {cleared} previously-banned user(s).")

    # --- startup security sweep (catch offline joins) -----------------------
    swept = await sweep_members()
    if swept:
        ui.success(f"Startup sweep removed {swept} non-admin member(s).")
        await notify(f"Startup sweep removed <b>{swept}</b> member(s).")

    # --- run ----------------------------------------------------------------
    # Raw participant updates catch broadcast-channel joins; ChatAction is a
    # backup for supergroups. Listen to ALL raw updates and filter in-handler
    # (a type-filtered Raw can miss updates on some layers).
    client.add_event_handler(on_participant, events.Raw)
    client.add_event_handler(on_chat_action, events.ChatAction(chats=channel))
    asyncio.create_task(rotate_loop())
    asyncio.create_task(sweep_loop())

    sweep_note = (f"security sweep every {config.SWEEP_MINUTES:g} min; "
                  if config.SWEEP_MINUTES > 0 else "")
    title = getattr(channel, "title", channel)
    ui.banner("Channel guard - running")
    ui.success(f"Guarding: {ui.bold(str(title))}")
    ui.info(f"Owner: {getattr(owner, 'first_name', owner.id)} (id {owner.id})")
    ui.info(f"Rotating invite link every {ui.bold(f'{config.ROTATE_MINUTES:g}')} min; "
            f"{sweep_note}joiners are kicked + unbanned (no lasting ban). "
            + ui.dim("Ctrl+C to stop."))
    await client.run_until_disconnected()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nStopped.")
